quantumrobotics/arduinodata/urls.py
from django.urls import path

from . import views 
from .views import IndexListView

app_name='arduinodata'
urlpatterns = [
    path('',IndexListView.as_view(), name='index'),
    path('model/<str:board>/', views.model, name='model'),
    path('registers/<str:model_board>/', views.data, name='arduino-data')
]

quantumrobotics/quantumrobotics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('arduinodata/', include('arduinodata.urls')),
    path('/', RedirectView.as_view(url='/catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quantumrobotics/arduinodata/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.

class Arduino(models.Model):
    BOARD = (
        ('EL',"Entry Level"),
        ('EF',"Enhanced Features"),
        ('IoT', "Internet of Things"),
        ('RET','Retired')
    )
    board = models.CharField(verbose_name="Board",max_length=3, choices=BOARD)
    board_name = models.CharField(max_length=255)
    def __str__(self):
        return f"{self.board} - {self.board_name}"
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('arduinodata:arduino-data', kwargs={'pk' : self.pk})

class Data(models.Model):
    arduino = models.ForeignKey(Arduino, on_delete=models.CASCADE)
    sensor = models.IntegerField(default='0')
    content = models.TextField(verbose_name="Content",default='')
    date = models.DateField(verbose_name="Date",default='')
    def __str__(self):
        return f"Sensor {self.sensor} - {self.arduino.board_name} - {self.date}"

class ArduinoForm(ModelForm):
    class Meta:
        model = Data
        fields = ['arduino', 'sensor', 'content']

quantumrobotics/arduinodata/views.py
from django.db.models.query_utils import Q
from django.http.response import HttpResponse
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView
from django.http import Http404, HttpResponseRedirect
from .models import Arduino, Data
from django.views.generic.detail import DetailView
from django.urls import reverse
from .models import Data
from datetime import datetime
from .models import ArduinoForm
# Create your views here.

class IndexListView(ListView):
    model=Arduino
    template_name='arduinodata/index.html'
    def get_context_data(self,**kwargs):
        context = super(IndexListView, self).get_context_data(**kwargs)
        board=Arduino.BOARD
        boards=[]
        boards_key=[]
        for i in range(len(board)):
            boards_key+=[board[i][0]]
            boards+=[board[i][1]]
        
        hard_by_model=[]
        for i in boards_key:
            hard_by_model+=[Arduino.objects.filter(board=i)]
        
        context['key_boards']=zip(boards_key,hard_by_model)
        context['value_boards']=zip(boards_key,boards)

        # Create the form class.
        form=context['form']=ArduinoForm()
        if form.is_valid():
            arduino = form.cleaned_data['arduino']
            print(arduino)
            sensor = form.cleaned_data['sensor']
            content = form.cleaned_data['content']
            date=datetime.today()
            data=Data(arduino=arduino,sensor=sensor,content=content,date=date)
            data.save()
            return HttpResponseRedirect(reverse('arduinodata:index'))
        
        return context

def model(request,board):
    board_keys=[]
    print(board)
    for i in Arduino.BOARD:
        board_keys.append(i[0])
    if board in board_keys:
        boards = Arduino.objects.filter(board=board)
        return render(request,"arduinodata/model.html",{
                "boards":boards,
                })
    else:
        raise Http404("No contamos con tal board")

def data(request,model_board):
    data=Data.objects.filter(arduino=model_board)
    
    return render(request, "arduinodata/data.html",{
        'data':data,
        })

quantumrobotics/arduinodata/templates/arduinodata/data.html
{% extends "arduinodata/layout.html" %}

{% load static %}

{% block head %}
    <!-- <script type="text/javascript" src="{% static 'arduinodata/js/index.js' %}"></script> -->
{% endblock %}

{% block body %}
<h1>Registros</h1>
<ol>
    {% for i in data %}
        <li>{{i}}</li>
    {% empty %}
        <li>No has registrado datos.</li>
    {% endfor %}
</ol>

{% endblock %}

quantumrobotics/arduinodata/templates/arduinodata/index.html
{% extends "arduinodata/layout.html" %}

{% load static %}

{% block head %}
    <title>Quantum Robotics</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'arduinodata/css/styles.css' %}" rel="stylesheet" />
    <script type="text/javascript" src="{% static 'arduinodata/js/index.js' %}"></script>
{% endblock %}

{% block body %}
<body class="d-flex flex-column h-100">
    {% for key,board in value_boards %}
        <button data-board={{key}}>{{board}}</button>
    {% endfor %}
    <h1>ARDUINO</h1>
    <div id="all_products">
        <ul>
        {% for arduino in arduino_list %}
            <li>{{arduino.board_name}}</li>
        {% endfor %}
        </ul>
    </div>
    <div id="models"></div>
    <h2>Save arduino's register</h2>
    <form>
        {% csrf_token %}
        {{form}}
    <input type="submit" id="oferta_compra" value="Save"> 
    </form>
    
</body>
{% endblock %}

quantumrobotics/arduinodata/templates/arduinodata/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quantum Robotics</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'arduinodata/css/styles.css' %}" rel="stylesheet" />
    <title>QuantumRobotics</title>
    {% block head%}
    {% endblock %}
</head>
<body class="d-flex flex-column h-100">
    <main class="navbar navbar-expand-lg navbar-dark bg-dark">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'arduinodata:index' %}">Quantum Robotics</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'arduinodata:index' %}">Arduino</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'arduinodata:index' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href="pricing.html">Hardware</a></li>
                        <li class="nav-item"><a class="nav-link" href="faq.html">FAQ</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </main>
    {% block body %}{% endblock %}
    <!-- Footer-->
    <footer class="bg-dark py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; arduinodata 2021</div></div>
                <div class="col-auto">
                    <a class="link-light small" href="#!">Privacy</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">Terms</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">Contact</a>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

quantumrobotics/arduinodata/templates/arduinodata/model.html
<h2>Boards</h2>
<ul>
    {% for board in boards %}
        <li><a href="{% url 'arduinodata:arduino-data' board.id %}">{{board.board_name}}</a></li>
    {% endfor %}
</ul>